### ISSUE TITLE
Lande-Ellipse als Shapfile

### ISSUE THREAD

**Issue by swalterfub** [swalterfub/jezero-map#10]
Projektion: Equirectangular lon0=0 R=3396190

**Comment by swalterfub** [comment]
Hieraus kann sie abdigitalisiert werden:
https://mars.nasa.gov/resources/25491/perseverance-rover-landing-ellipse-in-jezero-crater/

**Comment by swalterfub** [comment]
Ich glaube diese Landing Site ist Müll. Dann würde der Rover ja evtl. auf dem Delta landen!

**Comment by swalterfub** [comment]
@AliciaNeesemann , Du hast doch die Landeellipse für das LPSC abstract gemacht. Könntest Du sie bitte auf den Server kopieren? Danke!

**Comment by AliciaNeesemann** [comment]
@swalterfub Das Shapefile der Landeellipse ist jetzt in den entsprechenden Ordner auf Proteus (/mnt/storage/hrsc-mos/jezero/Shapefiles_CTX-based/Alicia). 

Die Landeellipse liegt bei 18.4475°N/77.4565°E mit semi-major- und semi-minor Achsen (Radien) von 4.49 und 4.02 km. Da ich die Ellipse damals aber selbst aus den Planungspraesentationen digitalisieren musste, mag das im Verhaeltnis zur 'echten' Ellipse um ne Nachkommastelle variieren ;)

**Comment by AliciaNeesemann** [comment]
@swalterfub @wzuschneid @ChristophGrossFUB @bpschreiner

In dem Shapefile Ordner ist nun neben anderen Shapefiles auch ein Point Shapefile mit den aus mehreren Kratermessungen ermittelten center coordinates von Jezero. Aus eigener Erfahrung weiß ich, daß eigene Messungen dann doch oft genauer sind, als die bei der IAU hinterlegten Werte.

**Comment by swalterfub** [comment]
Hier was interessantes zur Landeellipse: https://www.planetary.org/space-images/mars-2020-landing-technique

Scheint also tatsächlich so zu sein, dass das Delta in der Ellipse liegt, und dann aber den Hängen ausgewichen wird, um möglichst nah dran zu sein...
@AliciaNeesemann @wzuschneid @ChristophGrossFUB @bpschreiner

**Comment by swalterfub** [comment]
Irgendwas war mit dem Shapefile komisch, der Mapserver wollte es partout nicht anzeigen. Ich dachte es läge an den Layer Einstellungen, da es im GIS angezeigt wurde. Jetz habe ich es nochmal nachdigitalisiert...

**Comment by AliciaNeesemann** [comment]
Komisch. Hat sich denn in der Zwischenzeit ergeben woran es lag?

 

Von: Sebastian Walter <notifications@github.com> 
Gesendet: 12 February 2021 19:07
An: swalterfub/jezero-map <jezero-map@noreply.github.com>
Cc: Alicia Neesemann <a.neesemann@fu-berlin.de>; Mention <mention@noreply.github.com>
Betreff: Re: [swalterfub/jezero-map] Lande-Ellipse als Shapfile (#10)

 

Irgendwas war mit dem Shapefile komisch, der Mapserver wollte es partout nicht anzeigen. Ich dachte es läge an den Layer Einstellungen, da es im GIS angezeigt wurde. Jetz habe ich es nochmal nachdigitalisiert...
