### ISSUE TITLE
Press-Release Begleittext

### ISSUE THREAD

**Issue by swalterfub** [swalterfub/jezero-map#12]

**Comment by swalterfub** [comment]
Vergleich der Wassermenge mit bekanntem See

**Comment by swalterfub** [comment]
DLR: Von Aufnahmedaten über ein Bildmosaik zur topographischen Karte

Die Karte deckt bei etwa 18 Grad nördlicher Breite und 77 Grad östlicher Länge ein Gebiet von 6400 Quadratkilometern ab. Der Krater Jezero nimmt darin eine Fläche von etwa 2000 Quadratkilometern ein, das ist knapp die vierfache Fläche des Bodensees.
@HBalthi

**Comment by swalterfub** [comment]
Zm Vergleich: etwas kleiner als das Saarland mit 2569 km^2
@wzuschneid

**Comment by HBalthi** [comment]
Christoph, wie war das mit den Icons, die wir/du für die IP's benutzen wolltest? Wenn sie aus dem Internet kommen, müssen wir hier auch Copyrights angeben, oder behalten wir einfach nur die Punkte und Ferngläser bei.

**Comment by ChristophGrossFUB** [comment]
da überlassen wir Dominik würde ich sagen...

**Comment by swalterfub** [comment]
Ich verwende auch eine Menge Icons, die hier sind frei: https://fontawesome.com/start

**Comment by HBalthi** [comment]
Textbausteine
Der Weg von Perseverance – NASA’s Mars Rover
Der virtuelle Weg des Nasa-Rovers „Perseverance“

Erfahren Sie mehr über die geologischen Sehenswürdigkeiten auf dem Weg von „Perseverance“

Nach xx Tagen wird der NASA-Rover "Perseverence" heute um xxx Uhr auf unserem Roten Nachbarplaneten landen.

Kommen Sie mit auf einen virtuellen Weg und begleiten den kleinen NASA-Rover auf seiner Suche nach organischem Material, welches Hinweise auf früheres Leben auf dem Mars geben soll. Wir erklimmen mit Ihnen Mars-Berge und zeigen Ihnen interessante geologische Gebiete, in welchen der Rover Gesteinsproben nehmen wird, die von späteren Missionen zur Erde zurückgebracht und untersucht werden sollen.

Hier im Mapserver könne Sie den virtuellen Weg des Rovers im und um den Jezero Krater nachverfolgen. Das hier zu Grunde liegende Bildmosaik wurde aus vier Orbitstreifen der High Resolution Stereo Camera (HRSC) an Bord der Mars Express Mission der ESA erstellt und deckt ein Gebiet bei etwa 18 Grad Breite und 77 Grad Länge nördlich des Marsäquators ab. Das Mosaikbild wird mit topographischen Informationen aus den Stereokanälen der HRSC und XXXX kombiniert, so XXXX dass eine dreidimensionale Landschaft entsteht. Mitarbeiter der Fachrichtung Planetologie und Fernerkundung der Freien Universität Berlin erstellten daraus den hier gezeigten Mapserver. Die HRSC Kamera auf Mars Express wird vom Deutschen Zentrum für Luft- und Raumfahrt (DLR) betrieben. Die systematische Prozessierung der Kameradaten erfolgte am DLR-Institut für Planetenforschung in Berlin-Adlershof.


Der virtuelle Weg des Nasa-Rovers „Perseverance“
» Die geologischen Sehenswürdigkeiten auf dem Weg von „Perseverance“
Unterkapitel Text zum aufklappen

Allgemein – Ziele der Mission
Ziel der NASA Mars 2020 Mission ist die Erforschung der Geschichte und der Wasserchemie in einem ehemaligen Kratersee, des dazugehörigen Flussdeltas, die Untersuchung des frühen Marsklimas und die Suche nach Leben. Der Marsrover "Perseverance" hat zwei vielversprechende Technologie-Demonstrationen an Bord: Der Rover soll auf dem Mars Sauerstoff aus Kohlendioxid herstellen. Das MOXIE-Experiment (Mars Oxygen In Situ Resource Utilisation Experiment) stammt vom Massachusetts Institute of Technology (MIT) und wurde in Zusammenarbeit mit Ingenieuren des Jet Propulsion Laboratory (JPL) der Nasa entwickelt. Es soll zeigen, wie sich auf dem Mars aus vorhandenen Ressourcen Sauerstoff herstellen lässt - der dann nicht nur als Atemluft für künftige Astronauten, sondern auch als Treibstoff für Raketen dienen könnte.

Außerdem hat der Rover Perseverance einen kleinen Hubschrauber dabei, der ebenfalls auf dem Mars getestet werden soll. Ingenuity ist ein Hubschrauber von der Größe einer Drohne, der, wenn er erfolgreich ist, eine neue Perspektive für zukünftige Marsmissionen bieten könnte: Bislang war die Erkundung des Mars nur von der Oberfläche (Rover) oder aus dem Orbit (Orbiter) möglich. Ein Hubschrauber könnte den Mars aus verschiedenen Höhen und Perspektiven erkunden und später auch Astronauten auf dem roten Planeten unterstützen.

Außerdem ist geplant, dass der Marsrover "Perseverance" an bestimmten, besonders interessanten geologischen Stellen Gesteinsproben nimmt, welche von späteren Missionen zum Mars die Proben zur Erde zurück bringen - wo sie dann untersucht werden sollen.
Siehe auch Link: Flug über den Jezero Krater - NASA Mars 2020 Landestelle


outflow channel views  - 	Blick über den Abflusskanal
delta -   			Blick über das Delta
Inlet 1 -   			Ansicht Zulauf (Punkt 1)
Inlet 2 -   			Ansicht Zulauf (Punkt 2)
Jezero Crater  - 			Blick in den Krater Jezero
Vulcano - 			Blick zum Vulkan im Südosten

**Comment by HBalthi** [comment]
test @HBalthi

**Comment by ChristophGrossFUB** [comment]
Arbeitstitel Special PR: Jezero map and virtual views
Seit dem 30 Juli 2020 ist die NASA Mars 2020 Mission auf dem Weg zum Mars. An Bord der Raumsonde befindet sich der Rover „Perseverance“ (Beharrlichkeit). Er ist das komplexeste Gerät das jemals zum Mars geschickt wurde. Neben zahlreichen wissenschaftlichen Instrumenten wird er einen Behälter für Bohrkernproben mit sich führen. Die gesammelten Proben, verbleiben auf dem Mars und sollen durch eine spätere Mission, die für die 2030er Jahre geplant ist, zur Erde zurückgebracht werden. Das fast eine Tonne schwere Fahrzeug soll am 18. Februar 2021 um 21:55 Uhr im Krater Jezero landen und dort unter anderem nach Spuren früheren mikrobiellen Lebens suchen. „Ingenuity” (Einfallsreichtum) lautet der Name der 1,8 kg schweren Hubschrauberdrohne auf dem Rover, sie ist ein Technologiedemonstrator und Nahfeldaufklärungsinstrument. Der Jezero Einschlagskrater wurde aus guten Gründen ausgewählt. In dem Krater befinden sich zwei sehr alte Flussdeltas, in deren Ablagerungen zahlreiche wasserhaltige Minerale entdeckt wurden: ein Beweis dafür, dass dort Wasser in flüssigem Zustand für sehr lange Zeit vorhanden gewesen sein muss. 
Jezero ist ein ca. 49 km weiter Einschlagskrater, der sich am Rand des großen Isidis Einschlagsbeckens befindet, das entspricht etwa der vierfachen Fläche des Bodensees oder der Fläche von Mauritius. Der Krater entstand im Zeitalter „Noachium“, etwa 3,9 Milliarden Jahren vor unserer Zeit. Jezero beherbergte einst einen See, der von Zuflüssen aus großen regionalen Wassereinzugsgebieten gespeist wurde und an deren Mündung sich zwei Deltas im See gebildet haben. Die beiden ehemaligen Zuflusstäler Neretva Vallis und Sava Vallis sind im westlichen und nordwestlichen Teil des Kraters zu erkennen (Standpunkt X). Wasserhaltige Tonminerale, aber vor allem auch Karbonate, die im westlichen Delta in vergleichsweise großen Mengen auftreten, bergen ein hohes Potential der Konservierung möglicher Biosignaturen. Das frühere Vorhandensein von Wasser und die mächtigen Karbonatablagerungen machen Jezero zu einem perfekten Ziel für die Suche nach möglichem ehemaligem Leben auf dem Mars. 
Das Ausflusstal Pliva Vallis (Standpunkt Y) durchbricht den Kraterrand im Osten über eine Schwelle hinweg. Aus den Höhenangaben von Kraterrand, Kraterboden, Schwelle und Deltaoberkante lässt sich auch eine mögliche Tiefe des Kratersees ableiten die bei Jezero mindestens 250 Meter betragen haben dürfte. Da allerdings sowohl die Deltas, als auch die Schwelle am Ausflusstal nach Ende der Wasseraktivität vor etwa 3,8 Milliarden Jahren stark erodiert wurden, ist die eine minimale Wassertiefe. Darüber hinaus wurde der Krater etwa 300 Millionen Jahre später von mächtigen Lavaströmen der nahegelegenen Vulkanregion Syrtis Major verfüllt.
Einen guten Überblick in den Krater hinein erhält der Beobachter vom südöstlich gelegenen Berg aus (Standpunkt Z). Von hier aus wird deutlich, dass der nördliche Teil des Kraterbodens schräg abfallend und der Kraterrand weitaus weniger deutlich ausgeprägt sind, als der ebene, südliche Kraterboden und die steileren Südflanken. Grund dafür ist, dass Material im Einzugsgebiet nördlich des Kraters abgetragen, in das Kraterinnere verfrachtet und in den Deltas als Sedimente abgelagert wurde. Auch die Erosion des nördlichen Kraterrandes durch die durchbrechenden Flusstäler spielte bei der Bildung dieser asymmetrischen Topographie eine Rolle. Auf der topografischen Karte (Link zu unserer Karte) wird dies sehr deutlich.


Link zur Landing live:

https://mars.nasa.gov/mars2020/timeline/landing/

**Comment by wzuschneid** [comment]
@HBalthi 
@ChristophGrossFUB 
@wzuschneid 
Ein paar Verbesserungsvorschläge zum Text
Nach xx Tagen wird der NASA-Rover "Perseverence" heute um xxx Uhr auf unserem Roten Nachbarplaneten landen.
-> Perseverance mit A

Kommen Sie mit auf einen virtuellen Weg und begleiten **_SIE_** den kleinen NASA-Rover auf seiner Suche nach organischem Material, welches Hinweise auf früheres Leben auf dem Mars geben soll **_/ enthalten könnte_**. 
-> "Sie" ergänzt
-> "Hinweise geben" ist m.M. zu aktiv, deswegen Vorschlag "enthalten"

Hier im Mapserver könne Sie den virtuellen Weg des Rovers im und um den Jezero Krater nachverfolgen. 
-> "um" wird wohl eher zu weit sein?

Ich würde die beiden Technologiedemonstratoren tauschen, weil der Hubschrauber spannender und f.d. Mission wichtiger ist. 

... sondern auch als Treibstoff für Raketen dienen könnte
-> "zur Produktion von Treibstoff" wäre eher korrekt, weil der eigentliche Treibstoff (z.B. Kerosin oder Wasserstoff) den Sauerstoff als Oxidator braucht. Könnte man ändern, kann man aber auch stehen lassen.

Außerdem hat der Rover Perseverance einen kleinen Hubschrauber dabei,...
Normalerweise steht "Perseverance" in "" 

Ingenuity ist ein Hubschrauber von der Größe einer Drohne, der, wenn er erfolgreich ist, eine neue Perspektive für zukünftige Marsmissionen bieten könnte
-> "Ingenuity" in ""
-> , wenn er erfolgreich ist, : würde ich rauslassen, macht den Text nur komplizierter, und warum vom Scheitern reden :-)

Außerdem ist geplant, dass der Marsrover "Perseverance" an bestimmten, besonders interessanten geologischen Stellen Gesteinsproben nimmt, welche von späteren Missionen zum Mars die Proben zur Erde zurück bringen - wo sie dann untersucht werden sollen.
-> Besonders den zweiten Satzteil würde ich ändern: 
-> Außerdem ist geplant, dass der Marsrover "Perseverance" an bestimmten, geologisch besonders interessanten Stellen Gesteinsproben nimmt. Diese Proben sollen von späteren Missionen zur Erde zurückgebracht werden, wo Sie dann im Labor untersucht werden können.

**Comment by swalterfub** [comment]
Die Text sind super, ich würde sie dann auch noch bei den einzelnen Panoramen unter einem Info-Button unterbringen, damit man zu der jeweiligen Szene was dazu lesen kann...

**Comment by HBalthi** [comment]
@swalterfub
@ChristophGrossFUB 

Christoph wird für ESA und DLR einen englischen Text erstellen. Für unsere Seite (CMS) können wir ja noch ein bisschen iterieren. Aber für die Punkte **» information to image origin and processing**, wie auf unseren PRs unten: https://www.geo.fu-berlin.de/en/geol/fachrichtungen/planet/presse/2020_jezero_topo/index.html
benötigen wir noch die Angaben welche **Programme usw.** benutzt wurden.

**Comment by swalterfub** [comment]
Über die Ko-Registrierung von CTX (und den de-smile) kann auch @AliciaNeesemann beitragen, den Rest mache ich

**Comment by AliciaNeesemann** [comment]
Erst mal zur co-Registrierung

Gewoehnlicherweise werden pro Bild 20-30 equidistant verteilte tie points genommen (siehe beispielsweise ASP documentation, Seite 69, Section 8.3. Fuer Images der Dawn Framing Camera beispielsweisehat sich aus meiner Erfahrung gezeigt (und ich habe locker 2500 einzelne Bilder mit tie points versehen), daß 25 tie Points fuer eine Framing Camera ein ganz guter Wert fuer das bundle adjustment sind. Noch mehr tie points fuehren in der Regel zu keiner großen Verbesserung. Schwieriger wird es aber natuerlich bei push-broom Kameras, welche nun mal Bildern it x=y liefern, sondern deren Laege ja nur durch den Speicher begrenzt ist. Eine optimale Verteilung von tie points fuer push-broom Kameras zu bestimmen, ist daher etwas schwieriger. Dennoch achte ich bei CTX Daten immer auf eine equidistante Verteilung von tie points. Die 5000 CCDs (Sensorbreite) sind bei mir durch 5 tie points abgedeckt. Bei 5 tie points in Sample Richtung ergibt sich relativ oft (zumindest bei den fuer Jezero verwendeten CTX swaths) eine Anzahl an 9 oder 17 tie points in Line Richtung. Jeder CTX swaths ist damit durch mindestens 45 und hoechstens 85 tie points abgedeckt.

Die CTX Daten sind waehrend der SPICE ingestion auf Basis des MC13E DTMs orthorektifiziert, und im Anschluss auf einzelne lev-4 Orbits (0988 und 5270) und den lev-3 Orbit 5252 (den gabs noch nich als lev-4). Verbessern laesst sich die Orthorektifizierung bzw. Erstellung von Orthoimages erst mit dem CTX DTM.

**Comment by AliciaNeesemann** [comment]
Smile Korrektur

Ich nehme die Smile Korrektur empirisch vor. Und zwar lege ich sieben verschiedene Profile entlang der samples an geeigneten Stellen, an denen der smile Effekt so geringfuegig wie moeglich durch reale, geomorphologisch oder mineralogisch bedingte Helligkeitsunterschiede beeinflusst ist. Aus den sieben provielen rechne ich ein Durchschnittsprofil und approximiere dieses mit einer Polynomfunktion 2ten Grades. Diese wird dann bei sample 2500 und 2501 invertiert und wiederum modelliert. Die resultierende Funktion ist dann die Korrekturfunktion, mit der der Smile Effekt gut korrigiert werden kann - wie man ja anhand der vielen CTX swaths sehen kann.

Braucht ihr die Funktionen fuer jeden einzelnen swath? Ich habe die natuerlich nicht geloescht.

**Comment by HBalthi** [comment]
@AliciaNeesemann 
@ChristophGrossFUB 
@swalterfub 

Ich glaube, dass versteht kein Mensch und es ist zu ausführlich, aber egal ;)
Wir bräuchten das alles in englisch, die deutsche Version benötige ich nächste Woche fürs CMS.

Eigentlich hätte ich es gerne so, wie bei den PRs sonst, hier im ersten Absatz und bei den Credits (zumindest so ähnlich wäre schön). Die letzten beiden Absätze müssten ja eh bleiben.

**Image Prozessing** 
The images were acquired by the HRSC (High Resolution Stereo Camera) on XX and XX during Mars Express Orbit "5252, 5270, XX". The ground resolution is approximately XX metersper pixel. The "color mosaic" consists of four orbit strips ("5252, 5270") andcovers an area at about 18 degrees latitude and 77 degrees longitude north ofthe Martian equator. The XX map is based on a digitalterrain model (DTM) of the region, from which the topography of the landscapecan be derived. The reference body for the HRSC-DTM is a "Mars equipotentialsurface (Areoid)". XXXXX 

The HRSC camera on Mars Express is operated by the German Aerospace Center (DLR). Thesystematic processing of the camera data took place at the DLR Institute forPlanetary Research in Berlin-Adlershof. The working group of Planetary Scienceand Remote Sensing at Freie Universität Berlin used the data to create the filmshown here.

Image Credits 
Images: ESA/DLR/FU Berlin, CC BY-SA 3.0 IGO 

Copyright Notice: 
Where expressly stated, images arelicenced under the Creative Commons Attribution-ShareAlike 3.0 IGO (CC BY-SA3.0 IGO) licence. The user is allowed to reproduce, distribute, adapt,translate and publicly perform it, without explicit permission, provided thatthe content is accompanied by an acknowledgement that the source is credited as'ESA/DLR/FU Berlin', a direct link to the licence text is provided and that itis clearly indicated if changes were made to the original content. Adaptation /translation / derivatives must be distributed under the same licence terms asthis publication.

Camera
The High Resolution Stereo Camera wasdeveloped at the German Aerospace Center (DLR) and built in collaboration withpartners in industry (EADS Astrium, Lewicki Microelectronic GmbH andJena-Optronik GmbH). The science team, which is headed by PrincipalInvestigator (PI) Professor Ralf Jaumann, consists of 52 co-investigators from 34institutions and 11 countries. The camera is operated by the DLR Institute of PlanetaryResearch in Berlin-Adlershof.

**Comment by HBalthi** [comment]
@AliciaNeesemann 
[PR-Text-Working title Mars 2020 special PR_CG.docx](https://github.com/swalterfub/jezero-map/files/5966220/PR-Text-Working.title.Mars.2020.special.PR_CG.docx)

**Comment by AliciaNeesemann** [comment]
@swalterfub , @ChristophGrossFUB  , @wzuschneid  , @HBalthi 

Ich schreiben den Image Processing part mal neu und pflanze dann gleich die CTX Geschichte mit ein. Dauert aber bestimmt so 1-2 Stuendchen. Ich schicks im Anschluss rum.

**Comment by AliciaNeesemann** [comment]
@swalterfub @ChristophGrossFUB @wzuschneid @HBalthi 

Hier mal das update zum Text...(da das CTX DTM noch nicht fertig ist und daher in dem PR Release noch nicht vorkommt, muss die ganze Prozessierungskette die dafuer notwendig ist, auch nicht erwaehnt werden. Sagt Bescheid, ob da noch was fehlt.

Image data

For the Mars 2020 Perseverance Rover landing site or Jezero crater special PR release, a variety of data form the Mars Express (MEx) and Mars Reconnaissance Orbiter (MRO) were utilized. Base maps were created from panchromatic and RGB image data acquired by the High Resolution Stereo Camera (HRSC) at an average ground resolution of 12.5 m/px and 25.0 m/px, respectively. From the nine individual orbits covering Jezero crater to the present day, we made use of the four level-4 (orthorectified on HRSC Digital Terrain Models (DTM)) archived and publicly available ones (h0988, h5252, h5270, and h7289) acquired in 2004, 2008 and 2009. Topographic information is taken from the bundle-adjusted level-5 HRSC-based DTM of the eastern half of the MC13 Syrtis Major quadrangle and is presented in deviations from the Mars Global Surveyor (MGS) gravity and laser altimeter analysis derived Mars areoid.
To get a more detailed impression of the Mars 2020 Perseverance Rover landing site, a large number of higher resolution image data from the Context Camera (CTX) and the High Resolution Imaging Science Experiment (HiRISE) on board MRO were incorporated. In total, 33 CTX swaths having an average resolution of 6 m/px were orthorectified and co-registered to lev-4 and lev-5 HRSC data by bundle adjustment, using the USGS Integrated Software for Imagers and Spectrometers (ISIS) (https://isis.astrogeology.usgs.gov/). In a next step, these images were merged with the lower resolved HRSC-based RGB data to produce higher resolved pan-sharpened CTX-HRSC colour data.

**Comment by HBalthi** [comment]
@AliciaNeesemann 
@ChristophGrossFUB 
@swalterfub 

Wäre dann so:
[967-20210211-txt-spec-Mars2020-landing.docx](https://github.com/swalterfub/jezero-map/files/5967129/967-20210211-txt-spec-Mars2020-landing.docx)

**Comment by HBalthi** [comment]
@ChristophGrossFUB 
@swalterfub 
@bpschreiner @wzuschneid 
@AliciaNeesemann 

Und was meint ihr zum Text von C.G. und A.N...siehe oben.
Ich muss noch alles hochladen und der ESA/DLR was schreiben....

**Comment by swalterfub** [comment]
@HBalthi Meine Änderungen sind jetzt hier https://github.com/swalterfub/jezero-map/blob/main/Begleittext.md
Bitte Bescheid geben, falls es nicht abrufbar ist. Das Dokument kann auch nachverfolgbar geändert werden über den Edit Knopf oben rechts.

**Comment by swalterfub** [comment]
@ChristophGrossFUB @AliciaNeesemann bitte schaut Euch den Text auch nochmal an ob es für Euch hinnehmbar ist, wie ich Eure Inputs verwurstet habe.

**Comment by HBalthi** [comment]
Ich finde es gut so ;)

**Comment by swalterfub** [comment]
@HBalthi Bitte nochmal auf dem Server aktualisieren, habe ersten Absatz geändert (contains... contains) und die image credits für NASA Kameras ergänzt.

**Comment by swalterfub** [comment]
@ChristophGrossFUB könntest Du für dieses noch einen Text liefern? Dann würde ich das noch mit reinnehmen, das geht auch ohne weitere Entwicklungen: https://dneu.userpage.fu-berlin.de/paleo_lake_view.html

**Comment by ChristophGrossFUB** [comment]
Hier auf die Schnelle....
ich weiss allerdings nicht wirklich wie Björn bzw. Dominik das wirklich
gemacht haben, aber für den Anfang muss das reichen.

This view was created by plotting an estimated former lake level derived
from putative paleolake-shorelines and the upper delta-top boundary. The
Jezero crater lake must have been filled with water even more to overcome
the swell of the Pliva Vallis outflow channel.


C.

**Comment by bpschreiner** [comment]
Ableitung der Wasserflächen: Der obere Wasserspiegel bedeckt gerade den
Schwemmfächer im Westen, der untere erreicht gerade die Höhe der
Abflußschwelle om Osten. Volumen wurde berechnet durch Aufsummierung der
unter jedem Pixel (50x50m) der Wasserfläche stehenden Wasserhöhe
(=Wasserfläche - DTM).

-Björn

> Hier auf die Schnelle....
> ich weiss allerdings nicht wirklich wie Björn bzw. Dominik das wirklich
> gemacht haben, aber für den Anfang muss das reichen.
>
> This view was created by plotting an estimated former lake level derived
> from putative paleolake-shorelines and the upper delta-top boundary. The
> Jezero crater lake must have been filled with water even more to overcome
> the swell of the Pliva Vallis outflow channel.
>
>
> C.
>
>
>
>> @ChristophGrossFUB könntest Du für dieses noch einen Text liefern? Dann
>> würde ich das noch mit reinnehmen, das geht auch ohne weitere
>> Entwicklungen: https://dneu.userpage.fu-berlin.de/paleo_lake_view.html
>>
>> --
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/swalterfub/jezero-map/issues/12#issuecomment-780761506
>
>
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/swalterfub/jezero-map/issues/12#issuecomment-781076261


-- 
Dipl.-Geophys. Björn Schreiner
Freie Universität Berlin
Institut für Geologische Wissenschaften
Planetologie und Fernerkundung
Malteserstr. 74-100, Haus D
12249 Berlin
Tel. +49-30-838 70626
Fax. +49-30-838 70723

**Comment by ChristophGrossFUB** [comment]
dann passt es ja ;-)

**Comment by swalterfub** [comment]
Paleo Lake ist jetzt auch drin!
