### ISSUE TITLE
Landestelle als lat-lon Angabe

### ISSUE THREAD

**Issue by swalterfub** [swalterfub/jezero-map#13]
Kommt dann in Mapserver.

Quellen dazu?

Sollte dann entsprechend aktualisiert werden

**Comment by swalterfub** [comment]
Landestelle laut @AliciaNeesemann bei 77.4565°E/18.4475°N.

**Comment by AliciaNeesemann** [comment]
@swalterfub Naja, laut Alicia hoert sich so offiziell an. Letztendlich sind das die center coordinates der Ellipse, die ich von einem der Landing site workshops presentationen digitalisiert habe. Ich glaub es war entweder dieser (https://marsnext.jpl.nasa.gov/workshops/2018-10/LSSA_Quicklook_Preview_20180727_v2.pdf) (Seite 3) oder diese (https://marsnext.jpl.nasa.gov/workshops/2018-10/PRESENTATIONS/m2020_lsw_day2_12_mangold.pdf) (Seite 2). Letztendlich sind die beiden Ellipsen in den zwei Praesentationen soweit man das aus den Abbildungen erkennen kann, identisch.
