### ISSUE TITLE
Bessere DTMs und Farbbilder z.B. HiRise für @DominikNeuFU

### ISSUE THREAD

**Issue by swalterfub** [swalterfub/jezero-map#15]
Höhe passend zu HRSC
Ausmasse bekannt in lat/lon
Dazu passendes Ortho

**Comment by swalterfub** [comment]
@DominikNeuFU, wie groß kann denn das hochaufgelöste DTM und das zugehörige Ortho maximal sein?
Das komplette HiRise DTM Mosaik hat 21400 mal 21488 Pixel bei 1m Auflösung und 1,8 GB Speicher.
Das zugehörige Ortho hat 85600 mal 85952 Pixel bei 25 cm Auflösung und hat 6,9 GB.

**Comment by swalterfub** [comment]
In \\\proteus\hrsc-mos\jezero\HiRise liegt ein DTM und ein Ortho in jeweils voller Auflösung (siehe oben). 
Die Lat,Lon Ausmaße sind 77.2229331, 18.3067994  77.583964,18.669315
Ich kann sie aber auch noch in verschiedenen Stufen runterskaliert ablegen, Faktor 2, 4 8 16 usw... OK?
Farbversion folgt.

**Comment by DominikNeuFU** [comment]
DTM mit 1,8 GB sollte kein Problem sein. Ortho mit 6,9 GB schon eher. Werde es morgen mal testen.

**Comment by DominikNeuFU** [comment]
Das Grauwert-Ortho-Bild von HiRISE bekomme ich nicht in Cinema4D 
geladen. Zu groß. Werde es mal in 4 Stücke kacheln und dann reinladen.

Am 1/28/2021 um 10:06 PM schrieb Sebastian Walter:

**Comment by DominikNeuFU** [comment]
Habe mal die HiRISE-Daten in Cinema4D geladen. Habe sie aber in 4 Kacheln zerlegt und eine davon in C4D gepackt. Geht soweit erstmal und paßt auch mit dem Rest der Daten. Wenn ich dann aber rendern will, läuft der Arbeitsspeicher auf Kerwan schnell voll und er braucht für Bilder, für die er bei CTX+HRSC-DTM ca. 7-8 min brauchte, deutlich mehr als ne halbe Stunde. Muß da nochmal Optimierung betreiben, HRSC und CTX für solche Detailbilder abspecken, ohne daß es sichtbare Reduzierungen in den Bildern gibt.

**Comment by swalterfub** [comment]
Ja muss dann abgespeckt werden. Die Farb-Version von HiRise ist ja auch nochmal um den Faktor drei größer!

**Comment by DominikNeuFU** [comment]
Bekomme zwar die HiRISE-Daten als 4 einzeln gekachelten Stücken in Cinema geladen und von der Passgenauigkeit stimmt auch alles, aber eine DTM-Auflösung mit 1m bekomme ich selbst mit einer einzelnen Kachel nicht annähernd hin. Bei 115 Mrd. Punkten geht der Rechner in die Knie. Bin noch am Optimieren was Bildgrößen angeht, damit man für kleinere Bereiche die maximale Auflösung herausholen kann.

**Comment by DominikNeuFU** [comment]
Bekomme HiRISE-DTM bis auf 1,5m Auflösung in Cinema erstellt. Gibt es das Orthobild auch irgendwo in Farbe? Würden sonst die CTX-Farbdaten nehmen.

**Comment by swalterfub** [comment]
Im gleichen Ordner `\\\proteus\hrsc-mos\jezero\HiRise` liegt jetzt auch das Farbbild `JEZ_hirise_soc_006_orthoMosaic_25cm_Eqc_latTs0_lon0_first_hsv_hrsc.tif`
Hat allerdings eine Größe von 19 GB... mit dem GIS ist es aber flüssig anzuschauen, da Pyramiden auch dabei sind.

**Comment by DominikNeuFU** [comment]
![hiRISE_offset](https://user-images.githubusercontent.com/78101263/107246340-73e08300-6a30-11eb-87a0-fd57278aae90.jpg)

Habe zwischen dem HiRISE-DTM und dem Orthobild einen Versatz. Projektionen sind genau identisch. Passen trotzdem nicht aufeinander. Kannst du das mal prüfen?

**Comment by swalterfub** [comment]
Also ich habe mir die beiden Datensätze sehr genau angeschaut, und es sieht alles gut aus. Vielleicht kommt er nicht damit klar, dass es zwei verschiedene Auflösungen sind? Ich habe beide Raster mal als 2x2m runtergerechnet nochmal dort abgelet (mit identischer Auflösung und identischen Ausmaßen). Dort liegt auch ein Json file, falls Du den Extent nochmal brauchst.

**Comment by DominikNeuFU** [comment]
Habe den Fehler gefunden. War eine falsche Projektionseinstellung in Cinema.
