### ISSUE TITLE
PR Webseite im CMS erstellen

### ISSUE THREAD

**Issue by swalterfub** [swalterfub/jezero-map#19]

**Comment by swalterfub** [comment]
@HBalthi könntest Du bitte schonmal eine Vorlage anlegen im CMS? Ich würde gerne mal ausprobieren, wie sich die Karte als iframe darin einbetten lässt. Wir sollten ja Donnerstag der ESA/dem DLR die Adresse mitteilen...

**Comment by HBalthi** [comment]
Ja, wollte ich morgen mal erstellen....

**Comment by HBalthi** [comment]
So könnte es aussehen....Verlinkungen und richtige Bilder müssen noch rein
#19
![Website-test](https://user-images.githubusercontent.com/78091621/107397335-dacc6d80-6afe-11eb-8731-098ebd443596.jpg)

**Comment by HBalthi** [comment]
@swalterfub 
@bpschreiner 
@ChristophGrossFUB 
@HBalthi 
Daten für PR auf storage:Y:\fub\pr-activity\esa-pending\967_Landing-Jezero-18-2-21   abgelegt

Anaglyphe liegt im Ordner als: jezero_anaglmos.tif

Orbits sind 19922 und 19989 (j922, j989) in halber Auflösung. Umbedingt
mit Zoomify voll vergrößerbar machen. 8MB langen allenfalls für eine
Briefmarke.

Grüße,

-Björn

**Comment by swalterfub** [comment]
@HBalthi kannst Du mir den Pfad im CMS mal schicken bitte?

**Comment by swalterfub** [comment]
@HBalthi ich habe einen Unterordner mit dem iFrame erstellt, kannst Du das in die Seite einbinden?

**Comment by swalterfub** [comment]
Habs rausgefunden ;)

**Comment by swalterfub** [comment]
Kannst Du hier aus "Download zum Mapserver" besser "Link zum Mapserver" machen?
![image](https://user-images.githubusercontent.com/17708084/107549403-15520b00-6bd0-11eb-8947-12f1703eb1d1.png)

**Comment by HBalthi** [comment]
ist leider vorgegeben, kann ich nix ändern
<img width="692" alt="Bildschirmfoto 2021-02-10 um 18 55 25" src="https://user-images.githubusercontent.com/78091621/107550638-9362e180-6bd1-11eb-8712-0a521810c703.png">

**Comment by HBalthi** [comment]
@swalterfub 
Ich fand "Downloads" auch ungünstig, vielleicht fällt mir noch was ein... habe es auch schon mal ohne irgendwo erstellt....

**Comment by HBalthi** [comment]
Ach, ich weiß bei den Erklärbildchen, aber dann kann man nicht reinzoomen. Das ist nicht das, was wir wollen ;(

**Comment by swalterfub** [comment]
Naja in dem Fall wäre es ausreichend, wie z.B. hier: https://www.geo.fu-berlin.de/geol/fachrichtungen/planet/presse/2020_dark_angel/index.html bei dem Schema, nur dass dann nicht das Bild aufgeht, sondern der Link zum Mapserver (alles hinter jezero/ kannst Du übrigens weglassen). Bitte auch nicht die .../dist Version verwenden.

**Comment by HBalthi** [comment]
Probiere ich morgen mal aus...

**Comment by HBalthi** [comment]
@swalterfub 
@ChristophGrossFUB 

So könnte es nächste Wo aussehen.....
![Website-test](https://user-images.githubusercontent.com/78091621/107639199-d88a2080-6c70-11eb-945d-e0ea31ac44e9.jpg)

**Comment by swalterfub** [comment]
@HBalthi kann ich mir die Preview nochmal ansehen? Ich bilde mir ein, Du hattest dazu nochmal was rumgeschickt?... Danke

**Comment by swalterfub** [comment]
Wo ist denn die englische Seite eigentlich?

**Comment by swalterfub** [comment]
Sorry habs gefunden!
