### ISSUE TITLE
Kommunikation mit DLR+ESA

### ISSUE THREAD

**Issue by swalterfub** [swalterfub/jezero-map#20]
@ChristophGrossFUB Ankündigung 3.2.

PR aus Daten von letzten Jahr, bauen alles gerade zusammen, fertig am 11.2. (hoffentlich)

**Comment by ChristophGrossFUB** [comment]
Dear all, we envisage to publish a PR with material we produced last year to feature the Mars 2020 landing. It will feature a map-server containing different panoramic 360° views from Jezero crater, the landing site and other points of interest. Our currently unexisting resources for PR make this project challenging, but we will try to get ready for download of the data until February 11. Publication date would then be on February 18, the day of the landing.  Best regards, Christoph
