### ISSUE TITLE
Diese 3D Ansicht

### ISSUE THREAD

**Issue by swalterfub** [swalterfub/jezero-map#26]
@DominikNeuFU könntest Du bitte auch mal diese 3D Ansicht mit echten Daten rendern (HRSC ohne Wasser reicht erstmal):
![image](https://user-images.githubusercontent.com/17708084/107073060-27eecd80-67e7-11eb-9ec2-9e7170f3e0a5.png)
Das könnte ein Vulkan sein im Süd-Osten, das habe ich bisher noch nirgends gelesen...

**Comment by HBalthi** [comment]
@swalterfub 
uiiii, das mit dem sound in der map finde ich ja tollll!!!!!

**Comment by DominikNeuFU** [comment]
![paleo_lake_jezero2](https://user-images.githubusercontent.com/78101263/108068452-65aeea00-7062-11eb-917c-5b418cd92ac1.jpg)
![paleo_lake_jezero1](https://user-images.githubusercontent.com/78101263/108068501-765f6000-7062-11eb-9c46-4d3affea7681.jpg)

Lässt sich auch für die Panoramabilder rendern.

**Comment by swalterfub** [comment]
Danke!
