### ISSUE TITLE
Anaglyphe als Zoomify

### ISSUE THREAD

**Issue by swalterfub** [swalterfub/jezero-map#27]

**Comment by HBalthi** [comment]
@swalterfub 
so hat Heike mir früher die Links geschickt, die ich dann verlinkt habe...
https://www.planet.geo.fu-berlin.de/zoomify/Aurorae-Chaos/color-image.html

**Comment by swalterfub** [comment]
@HBalthi der link zur Anaglyphe als Zoomify: https://www.planet.geo.fu-berlin.de/zoomify/Jezero-Crater/anaglyph.html
Bitte issue schließen wenn im CMS erledigt
