### ISSUE TITLE
Anaglyphe in voller Auflösung auf proteus ablegen

### ISSUE THREAD

**Issue by swalterfub** [swalterfub/jezero-map#3]

**Comment by swalterfub** [comment]
Weiß nicht, wie man das im WebGIS einbinden könnte... aber vielleicht als Bestandteil der regulären PR auf der Webseite?

**Comment by HBalthi** [comment]
Ja, können wir im CMS machen, wie in den regulären HRSC-PRs.

**Comment by bpschreiner** [comment]
Vielleicht als Popup-Bild. Ungefähr skalieren auf die Karte geht ja noch,
aber die für den 3D-Effekt notwendige 90° Drehung torpediert die
Darstellung. Vielleicht kann man das irgendwie animieren, auf der Karte
liegt das Anaglyph in N-S Richtung wie der Rest ja auch, aber beim
Draufklicken öffnet sich ein Fenster, das sich quasi beim Öffnen sichtbar
im Uhrzeigersinn dreht. Zuviel Aufwand?

Grüße,

-Björn

> Weiß nicht, wie man das im WebGIS einbinden könnte... aber vielleicht als
> Bestandteil der regulären PR auf der Webseite?
>
> --
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/swalterfub/jezero-map/issues/3#issuecomment-773299799


-- 
Dipl.-Geophys. Björn Schreiner
Freie Universität Berlin
Institut für Geologische Wissenschaften
Planetologie und Fernerkundung
Malteserstr. 74-100, Haus D
12249 Berlin
Tel. +49-30-838 70626
Fax. +49-30-838 70723

**Comment by swalterfub** [comment]
Erweitertes Anaglyphen-Mosaik, Zoomify wäre schön

**Comment by swalterfub** [comment]
/share/hrsc-mos/jezero/HRSC/BS/Jezero_Anaglyphen-Mosaik/j989_j922_anaglmosaik_s2s1_1E.tif
