### ISSUE TITLE
Einzelbild-Renderings von Aussichtspunkten

### ISSUE THREAD

**Issue by swalterfub** [swalterfub/jezero-map#5]

**Comment by swalterfub** [comment]
@DominikNeuFU denkst Du bitte an den Screenshot mit den Aussichtspunkten? Kannst Du mir auch die Dateien für die pano360l.html Version schicken? Danke!

**Comment by DominikNeuFU** [comment]
Habe auf Github ein Repository für das Panorama-Projekt angelegt. Dort sollten nun alle derzeit genutzten Dateien drinliegen. Könntest vielleicht mal testen, ob das ganze auch offline auf einem lokalen Server funktioniert. Weiß nicht, ob die Javaskripte noch auf externe Sckripte zugreifen.

**Comment by swalterfub** [comment]
@DominikNeuFU  So könnte das dann in die Karte integriert werden (mal auf Marker clicken): https://maps.planet.fu-berlin.de/dist/

**Comment by HBalthi** [comment]
Super!!! Das sieht toll aus :)

**Comment by DominikNeuFU** [comment]
Auch eine gute Möglichkeit. Die Panoramabilder lassen sich aus dem 
WebGIS heraus bei mir allerdings nicht so flüssig bewegen.

**Comment by swalterfub** [comment]
Was ist das für ein Setup? Beim mir ist kein großer Unterschied, allerdings habe ich einen ziemlich aktuellen Rechner mit Grafikkarte. Läuft aber auch bei mir auf dem Handy, allerdings nicht flüssig.

**Comment by DominikNeuFU** [comment]
Ist ein Intel(R) Xeon(R) CPU  5130 mit 8GB RAM.

**Comment by swalterfub** [comment]
Hier ist die Stelle aus dem Lande-Movie. Vielleicht finden wir die in den Daten?

![image](https://user-images.githubusercontent.com/17708084/106900302-a6b80d80-66f6-11eb-82cb-4bd1f46ec24e.png)

**Comment by DominikNeuFU** [comment]
https://dneu.userpage.fu-berlin.de/Camera4_inflow_spheric.html

Update zum Zufluß.

**Comment by DominikNeuFU** [comment]
Die Kanten durch die unterschiedlichen Geländehöhen von HRSC zu HiRISE im DTM sind nun auch behoben.

**Comment by swalterfub** [comment]
Habe einen Zoom eingebaut, wie hier erklärt: https://stackoverflow.com/questions/44459356/a-frame-zoom-on-wheel-scroll

**Comment by DominikNeuFU** [comment]
Zoom funktioniert bei mir nicht. Aus dem WebGIS heraus?

**Comment by DominikNeuFU** [comment]
https://dneu.userpage.fu-berlin.de/Camera5_inflow_spheric.html

**Comment by DominikNeuFU** [comment]
Hier mal die Landestelle wie im Video auf https://mars.nasa.gov/mars2020/mission/science/landing-site/

https://dneu.userpage.fu-berlin.de/Camera14_landing_site_spheric.html

**Comment by swalterfub** [comment]
Mit dem Hubschrauber weiß ich allerdings nicht... da ja die anderen Bilder tendenziell von einem Wanderer ausgehen. Ist aber sehr lustig... wird bestimmt Aufregung geben, ob das echte Rover Bilder sind.

**Comment by swalterfub** [comment]
> https://dneu.userpage.fu-berlin.de/Camera5_inflow_spheric.html

Ist das auf dem Delta?

**Comment by DominikNeuFU** [comment]
Nein. Das ist unterhalb der Ausschwemmungen des Deltas im Osten. Auf dem Niveau mit dem kegelförmigen 'Berg'.

**Comment by HBalthi** [comment]
@DominikNeuFU 
Dominik, könntest du mir dieses Bild nochmal in einer höheren Ausflösung in den PR Ordner (storage: Y:\fub\pr-activity\esa-pending\967_spec-Mars2020-landing   legen, oder hast du es noch irgendwo anders zu liegen, von wo ich es mir selber ziehen kann?

![9FA87087-798A-440B-831E-F62F7B7CB47D_1_105_c](https://user-images.githubusercontent.com/78091621/107637004-c955a380-6c6d-11eb-8600-122ec8902d80.jpeg)

**Comment by DominikNeuFU** [comment]
https://dneu.userpage.fu-berlin.de/Camera15_center_crater.html

Panorama aus der Kratermitte.

**Comment by DominikNeuFU** [comment]
Und Landestelle mit Rover.

https://dneu.userpage.fu-berlin.de/Camera14_landing_site_spheric_rover.html

**Comment by swalterfub** [comment]
Kratermitte finde ich super, beim Rover weiß ich nicht, da fand ich das alte davor (mit der Drohne) besser.

Cool wäre noch eins mit dem Delta im Focus...

**Comment by DominikNeuFU** [comment]
> 
> 
> @DominikNeuFU
> Dominik, könntest du mir dieses Bild nochmal in einer höheren Ausflösung in den PR Ordner (storage: Y:\fub\pr-activity\esa-pending\967_spec-Mars2020-landing legen, oder hast du es noch irgendwo anders zu liegen, von wo ich es mir selber ziehen kann?
> 
> ![9FA87087-798A-440B-831E-F62F7B7CB47D_1_105_c](https://user-images.githubusercontent.com/78091621/107637004-c955a380-6c6d-11eb-8600-122ec8902d80.jpeg)

Habe unter storage: Y:\fub\pr-activity\esa-pending\967_spec-Mars2020-landing\Bilder eine neue Version dieser Perspektive abgelegt: Camera8_outflow_2.tif

**Comment by swalterfub** [comment]
@DominikNeuFU könntest Du bitte noch eine Szene von "Inlet 2" rechnen?  Dann eher auch von weiter oben, da Daten ja nur HRSC... Danke!

**Comment by DominikNeuFU** [comment]
Mache ich.

**Comment by DominikNeuFU** [comment]
Habe mal mein ganzes Panorama-Sammelsurium etwas geordnet.

http://dneu.userpage.fu-berlin.de/

**Comment by swalterfub** [comment]
Super danke. Könntest Du den "Mountain View" bitte auch noch mal neu rechen? War mal "sphere 2"... da sieht man aber noch deutlich die Farb-Pixel von HRSC, bei den späteren Versionen hatte ich das anders interpoliert.

**Comment by swalterfub** [comment]
Wie hoch ist die Überhöhung eigentlich? Und: Du hast die Farben nochmal behandelt oder?

**Comment by swalterfub** [comment]
@DominikNeuFU kannst Du bitte den jetzigen Mapserver mal checken, ob alle Szenen von Dir korrekt drinnen sind? Danke!

https://maps.planet.fu-berlin.de/jezero

**Comment by DominikNeuFU** [comment]
Soweit läuft alles. Den Bergausblick und die Landestelle ohne Heli rechne ich nochmal neu. Dann kommt noch der nördliche Zufluß. Das Abfluß-Panorama ist noch die ältere Fassung mit Wolken. Hatte ich auch noch mal neu gerechnet ohne Wolken.

**Comment by DominikNeuFU** [comment]
> 
> 
> Wie hoch ist die Überhöhung eigentlich? Und: Du hast die Farben nochmal behandelt oder?

Habe wegen der Überhöhung nochmal nachgemessen. Der Faktor ist ca. 1,6. Die Farben habe ich an sich nicht nochmal nachbearbeitet. Habe lediglich das Histogramm hinsichtlich Helligkeit angepasst.

**Comment by swalterfub** [comment]
Erstmal fertig, die paleo-lake Panoramen evtl. als post-release
